spring:  
  profiles:  
    active: dev  
  jackson:   
    date-format: yyyy-MM-dd HH:mm:ss  
    time-zone: Asia/Chongqing  
  freemarker: 
    suffix: .ftl
    templateEncoding: UTF-8
    templateLoaderPath: classpath:/templates/
    charset: UTF-8
    request-context-attribute: request
    content-type: text/html;charset=UTF-8
    
myProps: 
  simpleProp: simplePropValue  
  arrayProps: 1,2,3,4,5 